const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const dotenv = require('dotenv');
const path = require('path');

dotenv.config({ path: path.join(__dirname, '../.env') });

const User = require('../models/User');
const ExcavationSite = require('../models/ExcavationSite');
const Artifact = require('../models/Artifact');
const ExcavationLog = require('../models/ExcavationLog');
const Comment = require('../models/Comment');
const Notification = require('../models/Notification');

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('âœ… MongoDB Connected for ArchaeoTrack seeding...');
  } catch (err) {
    console.error('âŒ DB Connection failed:', err.message);
    process.exit(1);
  }
};

const seedData = async () => {
  await connectDB();

  try {
    console.log('ðŸ§¹ Clearing existing collections...');
    await Promise.all([
      User.deleteMany({}),
      ExcavationSite.deleteMany({}),
      Artifact.deleteMany({}),
      ExcavationLog.deleteMany({}),
      Comment.deleteMany({}),
      Notification.deleteMany({}),
    ]);
    console.log('âœ… Collections cleared.');

    // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    // USERS
    // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    console.log('ðŸ‘¤ Creating users...');
    const hashedPassword = await bcrypt.hash('password123', 12);

    const usersRaw = await User.insertMany([
      {
        name: 'Dr. Rajesh Sharma',
        email: 'admin@archrecords.com',
        password: hashedPassword,
        role: 'Admin',
        bio: 'Director General of Excavations at ASI. Specialist in Harappan urbanism, stratigraphy, and Indus Valley Civilization settlements with 25+ years of fieldwork.',
        expertise: ['Indus Valley Civilization', 'Urban Archaeology', 'Stratigraphy', 'Ceramic Typology'],
        institution: 'Archaeological Survey of India (ASI), New Delhi',
        phone: '+91-11-2301-8888',
        isActive: true,
      },
      {
        name: 'Dr. Priya Natarajan',
        email: 'lead@archrecords.com',
        password: hashedPassword,
        role: 'Lead Archaeologist',
        bio: 'Senior Epigraphist and Field Director for the Keeladi Tamil-Brahmi excavation. Leading authority on Sangam-era trade networks and Vaigai river valley settlements.',
        expertise: ['Epigraphy', 'Sangam Era', 'Tamil-Brahmi', 'Maritime Trade Routes'],
        institution: 'Tamil Nadu State Department of Archaeology, Chennai',
        phone: '+91-44-2345-6789',
        isActive: true,
      },
      {
        name: 'Dr. Anand Joshi',
        email: 'field@archrecords.com',
        password: hashedPassword,
        role: 'Field Assistant',
        bio: 'Archaeometallurgist specialising in ancient copper smelting technology and Harappan bead fabrication. Expert in micro-stratigraphy and GIS field survey methods.',
        expertise: ['Archaeometallurgy', 'Harappan Beadcraft', 'GIS Survey', 'Micro-Stratigraphy'],
        institution: 'Deccan College Post-Graduate and Research Institute, Pune',
        phone: '+91-20-2669-5678',
        isActive: true,
      },
      {
        name: 'Dr. Sunita Deshmukh',
        email: 'sunita@archrecords.com',
        password: hashedPassword,
        role: 'Lead Archaeologist',
        bio: 'Palaeobotanist and zooarchaeologist. Leads environmental reconstruction studies of ancient Indian agricultural and pastoralist communities from Neolithic to Iron Age.',
        expertise: ['Palaeobotany', 'Zooarchaeology', 'Neolithic South Asia', 'Environmental Reconstruction'],
        institution: 'Birbal Sahni Institute of Palaeosciences, Lucknow',
        phone: '+91-522-2297-0001',
        isActive: true,
      },
      {
        name: 'Dr. Vikram Mehta',
        email: 'viewer@archrecords.com',
        password: hashedPassword,
        role: 'Viewer',
        bio: 'Numismatist and art historian. Catalogues ancient Indian coins from the Mauryan, Gupta, and Kushan periods and studies iconographic traditions of early Buddhist monuments.',
        expertise: ['Numismatics', 'Buddhist Art', 'Gupta Period', 'Coin Iconography'],
        institution: 'National Museum of India, New Delhi',
        phone: '+91-11-2301-9272',
        isActive: true,
      },
    ]);

    const [admin, lead1, field1, lead2, viewer] = usersRaw;
    console.log(`âœ… Created ${usersRaw.length} users.`);

    // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    // EXCAVATION SITES
    // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    console.log('ðŸ›ï¸  Creating excavation sites...');

    const sitesRaw = await ExcavationSite.insertMany([
      {
        name: 'Rakhigarhi Archaeological Site',
        siteCode: 'RKG-2024',
        description: 'Rakhigarhi is the largest known site of the Indus Valley Civilization, spanning over 350 hectares across seven mounds in Hisar district, Haryana. The site has revealed extensive evidence of urban planning, craft production, and trade networks dating back to 5000 BCE. Current excavations under ASI have uncovered a necropolis, fire altars, a large granary complex, and numerous terracotta figurines and seals.',
        location: { country: 'India', region: 'Haryana', city: 'Hisar', address: 'Rakhigarhi Village, Hisar District, Haryana 125047', coordinates: { lat: 29.2783, lng: 76.1152 } },
        period: 'Mature Harappan (2600â€“1900 BCE)',
        era: 'Prehistoric',
        startDate: new Date('2022-01-15'),
        status: 'Ongoing',
        totalDepth: 7.5,
        areaSize: 125000,
        tags: ['Indus Valley', 'Harappan', 'Urban Planning', 'Bronze Age', 'Haryana'],
        createdBy: admin._id,
        teamMembers: [
          { user: admin._id, role: 'Principal Investigator' },
          { user: field1._id, role: 'Field Archaeologist' },
          { user: lead2._id, role: 'Environmental Specialist' },
        ],
      },
      {
        name: 'Dholavira Excavation Project',
        siteCode: 'DLV-2023',
        description: 'Dholavira, a UNESCO World Heritage Site on Khadir island in the Rann of Kutch, Gujarat, is one of the most remarkable ancient cities of the Indus Valley Civilization. The city is uniquely divided into three sections â€” a citadel, a middle town, and a lower town â€” with elaborate water conservation systems including 16 reservoirs and channels. The site has yielded the world\'s earliest signboard with Indus script, polished stone columns, and jewellery of exceptional quality.',
        location: { country: 'India', region: 'Gujarat', city: 'Bhuj', address: 'Khadir Island, Rann of Kutch, Gujarat 370165', coordinates: { lat: 23.8854, lng: 70.2097 } },
        period: 'Early to Late Harappan (2900â€“1500 BCE)',
        era: 'Prehistoric',
        startDate: new Date('2023-03-10'),
        status: 'Ongoing',
        totalDepth: 10.0,
        areaSize: 100000,
        tags: ['UNESCO', 'Indus Valley', 'Water Management', 'Kutch', 'Gujarat'],
        createdBy: admin._id,
        teamMembers: [
          { user: admin._id, role: 'Principal Investigator' },
          { user: lead1._id, role: 'Epigraphy Lead' },
          { user: field1._id, role: 'Field Archaeologist' },
        ],
      },
      {
        name: 'Keeladi (Keezhadi) Excavation',
        siteCode: 'KLD-2024',
        description: 'Keeladi, situated on the banks of the Vaigai River in Madurai district, Tamil Nadu, is a landmark urban settlement of the Sangam Period (6th century BCE â€“ 3rd century CE). The excavation has revealed remains of a sophisticated urban civilisation contemporary with the Mauryan Empire. Findings include Tamil-Brahmi inscriptions, terracotta figurines, gold ornaments, copper objects, and evidence of a flourishing textile industry.',
        location: { country: 'India', region: 'Tamil Nadu', city: 'Madurai', address: 'Keezhadi Village, Sivaganga District, Tamil Nadu 623806', coordinates: { lat: 9.8734, lng: 78.7346 } },
        period: 'Sangam Era (600 BCE â€“ 300 CE)',
        era: 'Ancient',
        startDate: new Date('2023-07-01'),
        status: 'Ongoing',
        totalDepth: 3.5,
        areaSize: 110000,
        tags: ['Sangam Era', 'Tamil-Brahmi', 'Vaigai River', 'Urban Settlement', 'Tamil Nadu'],
        createdBy: lead1._id,
        teamMembers: [
          { user: lead1._id, role: 'Field Director' },
          { user: field1._id, role: 'Field Archaeologist' },
          { user: viewer._id, role: 'Numismatic Consultant' },
        ],
      },
      {
        name: 'Lothal Port Town Excavation',
        siteCode: 'LTL-2023',
        description: 'Lothal, meaning "Mound of the Dead" in Gujarati, was a major trade port of the Indus Valley Civilization in Ahmedabad district, Gujarat. The site is famous for its ancient dockyard â€” arguably the world\'s earliest tidal dock â€” along with a unique bead factory, standardised weights, seals depicting trade goods, and evidence of maritime trade with Mesopotamia and the Persian Gulf civilisations.',
        location: { country: 'India', region: 'Gujarat', city: 'Ahmedabad', address: 'Lothal Village, Dholka Taluka, Ahmedabad District, Gujarat 382230', coordinates: { lat: 22.5241, lng: 72.2495 } },
        period: 'Mature Harappan (2400â€“1900 BCE)',
        era: 'Prehistoric',
        startDate: new Date('2023-01-20'),
        endDate: new Date('2024-03-31'),
        status: 'Completed',
        totalDepth: 4.5,
        areaSize: 70000,
        tags: ['Lothal', 'Dockyard', 'Maritime Trade', 'Harappan', 'Gujarat'],
        createdBy: field1._id,
        teamMembers: [
          { user: field1._id, role: 'Field Director' },
          { user: admin._id, role: 'Principal Investigator' },
          { user: lead2._id, role: 'Environmental Analyst' },
        ],
      },
      {
        name: 'Nalanda Monastery Complex Survey',
        siteCode: 'NLD-2024',
        description: 'Nalanda, once the greatest centre of learning in the ancient world, was a monastic university complex in Bihar that flourished from the 5th to 12th centuries CE. This ongoing survey maps the full extent of the 14-hectare UNESCO World Heritage Site, documenting intact stupa structures, vihara foundations, terracotta plaques of the Gupta period, bronze Buddhist sculptures, and an extraordinary collection of palm-leaf manuscript remnants.',
        location: { country: 'India', region: 'Bihar', city: 'Rajgir', address: 'Nalanda, Nalanda District, Bihar 803111', coordinates: { lat: 25.1369, lng: 85.4432 } },
        period: 'Gupta to Pala Period (5thâ€“12th century CE)',
        era: 'Classical',
        startDate: new Date('2024-01-10'),
        status: 'Ongoing',
        totalDepth: 2.0,
        areaSize: 140000,
        tags: ['Buddhist', 'Gupta Period', 'UNESCO', 'Monastery', 'Bihar'],
        createdBy: lead2._id,
        teamMembers: [
          { user: lead2._id, role: 'Site Director' },
          { user: viewer._id, role: 'Art History Consultant' },
          { user: admin._id, role: 'Oversight Archaeologist' },
        ],
      },
      {
        name: 'Hampi Vijayanagara Survey',
        siteCode: 'HMP-2023',
        description: 'Hampi, the ruined capital of the Vijayanagara Empire, is spread across 4,187 hectares on the banks of the Tungabhadra River in Karnataka. The site holds over 1,600 surviving structures including royal palaces, temples, market streets, elephant stables, and aquatic structures. Current field survey focuses on documenting previously unmapped peripheral zones, especially trade bazaars and craft-production quarters south of the royal enclosure.',
        location: { country: 'India', region: 'Karnataka', city: 'Hospet', address: 'Hampi, Vijayanagara District, Karnataka 583239', coordinates: { lat: 15.3350, lng: 76.4600 } },
        period: 'Vijayanagara Empire (14thâ€“17th century CE)',
        era: 'Medieval',
        startDate: new Date('2023-09-05'),
        status: 'Ongoing',
        totalDepth: 1.5,
        areaSize: 500000,
        tags: ['Vijayanagara', 'Medieval', 'UNESCO', 'Karnataka', 'Temple Architecture'],
        createdBy: admin._id,
        teamMembers: [
          { user: admin._id, role: 'Principal Investigator' },
          { user: lead1._id, role: 'Epigraphy Lead' },
          { user: field1._id, role: 'GIS Surveyor' },
        ],
      },
      {
        name: 'Sanchi Stupa Archaeological Project',
        siteCode: 'SCH-2023',
        description: 'The Sanchi Buddhist complex in Madhya Pradesh contains the oldest stone structures in India, dating to the 3rd century BCE during the reign of Emperor Ashoka. The ongoing project focuses on the conservation and detailed documentation of the four gateways (toranas) of the Great Stupa, epigraphic survey of the donative inscriptions, and sub-surface investigation of the surrounding settlement area using ground-penetrating radar.',
        location: { country: 'India', region: 'Madhya Pradesh', city: 'Vidisha', address: 'Sanchi, Raisen District, Madhya Pradesh 464661', coordinates: { lat: 23.4792, lng: 77.7396 } },
        period: 'Mauryan to Gupta Period (3rd BCE â€“ 12th CE)',
        era: 'Ancient',
        startDate: new Date('2023-11-01'),
        status: 'Ongoing',
        totalDepth: 3.0,
        areaSize: 40000,
        tags: ['Buddhist', 'Ashoka', 'UNESCO', 'Stupa', 'Madhya Pradesh'],
        createdBy: lead2._id,
        teamMembers: [
          { user: lead2._id, role: 'Principal Investigator' },
          { user: viewer._id, role: 'Epigraphic Consultant' },
          { user: field1._id, role: 'GPR Survey Specialist' },
        ],
      },
      {
        name: 'Mehrgarh Neolithic Outpost Survey',
        siteCode: 'MGH-2024',
        description: 'This project surveys satellite settlements in the Thar Desert of Rajasthan with cultural links to the Mehrgarh Neolithic tradition (7000â€“2500 BCE). Survey documents evidence of early wheat and barley cultivation, fired pottery, terracotta figurines, and copper metallurgy â€” all precursors to the Indus Civilisation. The project aims to trace the origins of South Asian urbanism from its earliest agricultural roots.',
        location: { country: 'India', region: 'Rajasthan', city: 'Barmer', address: 'Thar Desert Field Survey Zone, Barmer District, Rajasthan 344001', coordinates: { lat: 25.7455, lng: 71.3960 } },
        period: 'Neolithic (7000â€“3500 BCE)',
        era: 'Prehistoric',
        startDate: new Date('2024-02-01'),
        status: 'Planned',
        totalDepth: 6.0,
        areaSize: 25000,
        tags: ['Neolithic', 'Farming', 'Thar Desert', 'Rajasthan', 'Prehistoric India'],
        createdBy: lead2._id,
        teamMembers: [
          { user: lead2._id, role: 'Principal Investigator' },
          { user: field1._id, role: 'Survey Team Lead' },
        ],
      },
      {
        name: 'Taxila Gandhara Excavation',
        siteCode: 'TXL-2024',
        description: 'This project examines Gandhara-influenced Buddhist monasteries and relic deposits in the Punjab foothill zones, including fine schist sculptural fragments, relic caskets, and bilingual Kharosthi-Greek inscriptions reflecting Hellenistic-Indian cultural exchange during the 5th century BCE to 5th century CE period.',
        location: { country: 'India', region: 'Punjab', city: 'Pathankot', address: 'Pathankot Archaeological Zone, Punjab 145001', coordinates: { lat: 32.2742, lng: 75.6522 } },
        period: 'Gandhara Period (500 BCE â€“ 500 CE)',
        era: 'Classical',
        startDate: new Date('2024-03-15'),
        status: 'On Hold',
        totalDepth: 3.5,
        areaSize: 30000,
        tags: ['Gandhara', 'Buddhist', 'Hellenistic', 'Punjab', 'Silk Road'],
        createdBy: viewer._id,
        teamMembers: [
          { user: viewer._id, role: 'Project Lead' },
          { user: admin._id, role: 'Senior Advisor' },
        ],
      },
      {
        name: 'Ajanta Caves Conservation Survey',
        siteCode: 'AJT-2024',
        description: 'The Ajanta Caves in Aurangabad district, Maharashtra, contain 30 rock-cut Buddhist cave monuments dating from the 2nd century BCE to about 480 CE. This conservation survey documents the state of wall paintings, sculptural programmes, and vihara/chaitya structural integrity using high-resolution photogrammetry and multispectral imaging to reveal faded compositional elements invisible to the naked eye.',
        location: { country: 'India', region: 'Maharashtra', city: 'Aurangabad', address: 'Ajanta, Aurangabad District, Maharashtra 431117', coordinates: { lat: 20.5519, lng: 75.7033 } },
        period: '2nd century BCE â€“ 5th century CE',
        era: 'Ancient',
        startDate: new Date('2024-05-01'),
        status: 'Ongoing',
        totalDepth: 0.5,
        areaSize: 10000,
        tags: ['Buddhist', 'Rock-Cut', 'UNESCO', 'Paintings', 'Maharashtra'],
        createdBy: admin._id,
        teamMembers: [
          { user: admin._id, role: 'Conservation Director' },
          { user: lead2._id, role: 'Environmental Analyst' },
          { user: viewer._id, role: 'Art Historian' },
        ],
      },
    ]);

    console.log(`âœ… Created ${sitesRaw.length} excavation sites.`);
    const [rakhigarhi, dholavira, keeladi, lothal, nalanda, hampi, sanchi, mehrgarh, taxila, ajanta] = sitesRaw;

    // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    // ARTIFACTS
    // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    console.log('ðŸº Creating artifacts...');

    const artifacts = await Artifact.insertMany([
      // RAKHIGARHI
      {
        name: 'Rakhigarhi Terracotta Unicorn Seal',
        catalogNumber: 'RKG-ART-001',
        site: rakhigarhi._id,
        category: 'Inscriptions',
        material: 'Terracotta',
        estimatedAge: '2600â€“2000 BCE',
        era: 'Prehistoric',
        period: 'Mature Harappan',
        condition: 'Good',
        dimensions: { length: 3.8, width: 3.5, height: 1.2, weight: 45 },
        description: 'Square terracotta stamp seal depicting a unicorn-like animal (bull with single horn) with a feeding trough below. The reverse carries four Indus script signs. Found in trench RKG-T7, layer 4 at 2.3m depth, within a domestic context adjacent to a fire altar.',
        significance: 'Unicorn seals are among the most frequently found Indus artefacts and likely functioned as merchant identity markers in long-distance trade. This seal\'s excellent state of preservation makes it one of the finest examples from Rakhigarhi.',
        discoveryLocation: { gridReference: 'RKG-T7-L4', depth: 2.3, layer: 'Layer 4 â€“ Mature Harappan Occupation' },
        discoveredBy: admin._id,
        discoveredDate: new Date('2023-03-15'),
        tags: ['Harappan Seal', 'Unicorn', 'Indus Script', 'Trade'],
        storageLocation: 'ASI Regional Museum, Hisar â€“ Cabinet 3, Shelf B',
        isPublic: true,
        createdBy: admin._id,
      },
      {
        name: 'Terracotta Mother Goddess Figurine',
        catalogNumber: 'RKG-ART-002',
        site: rakhigarhi._id,
        category: 'Other',
        material: 'Terracotta',
        estimatedAge: '2500â€“2000 BCE',
        era: 'Prehistoric',
        period: 'Mature Harappan',
        condition: 'Fair',
        dimensions: { length: 8.5, width: 4.2, height: 12.0, weight: 180 },
        description: 'Standing female terracotta figurine with elaborate fan-shaped headdress, heavy necklaces, and a short skirt. The face is pinched with applied features. Traces of red ochre pigment remain on the lower body and headdress. Found in a ritual deposit in Mound 1.',
        significance: 'Mother Goddess figurines are found across all Indus Civilisation sites and represent one of the most debated aspects of Harappan religion, possibly associated with fertility cults or ancestor veneration.',
        discoveryLocation: { gridReference: 'RKG-M1-T3', depth: 1.8, layer: 'Layer 3 â€“ Late Mature Harappan' },
        discoveredBy: field1._id,
        discoveredDate: new Date('2023-05-22'),
        tags: ['Mother Goddess', 'Figurine', 'Religion', 'Ritual'],
        storageLocation: 'ASI Regional Museum, Hisar â€“ Cabinet 5, Shelf A',
        isPublic: true,
        createdBy: admin._id,
      },
      {
        name: 'Copper Fishing Hook with Barb',
        catalogNumber: 'RKG-ART-003',
        site: rakhigarhi._id,
        category: 'Tools',
        material: 'Copper',
        estimatedAge: '2300â€“2000 BCE',
        era: 'Prehistoric',
        period: 'Late Harappan',
        condition: 'Good',
        dimensions: { length: 4.5, width: 0.8, height: 0.5, weight: 12 },
        description: 'Well-preserved copper fishing hook with clear barb formation at the tip. Cast using the lost-wax method. Retrieved from a midden adjacent to a drainage channel in Mound 4, suggesting proximity to a water source.',
        significance: 'Demonstrates the Harappan mastery of copper metallurgy for utilitarian objects and confirms the economic importance of fishing and aquatic resource exploitation at Rakhigarhi.',
        discoveryLocation: { gridReference: 'RKG-M4-T12', depth: 1.5, layer: 'Layer 3 â€“ Midden Deposit' },
        discoveredBy: field1._id,
        discoveredDate: new Date('2023-08-10'),
        tags: ['Copper', 'Tool', 'Fishing', 'Metallurgy'],
        storageLocation: 'ASI Regional Museum, Hisar â€“ Cabinet 3, Shelf D',
        isPublic: true,
        createdBy: field1._id,
      },
      {
        name: 'Polished Carnelian Bead Necklace',
        catalogNumber: 'RKG-ART-004',
        site: rakhigarhi._id,
        category: 'Jewelry',
        material: 'Carnelian',
        estimatedAge: '2600â€“2000 BCE',
        era: 'Prehistoric',
        period: 'Mature Harappan',
        condition: 'Excellent',
        dimensions: { length: 45.0, width: 0.8, height: 0.8, weight: 85 },
        description: 'A complete necklace of 32 finely polished barrel-shaped carnelian beads of uniform size, found still strung together with preserved plant-fibre cord in a burial context. Provenance from a formal brick-lined grave in the Rakhigarhi cemetery area.',
        significance: 'This intact carnelian bead necklace confirms that beadmaking was a specialist craft at Rakhigarhi, with carnelian sourced from the Ratanpur mines of Gujarat. This level of craft standardisation implies organised inter-regional trade.',
        discoveryLocation: { gridReference: 'RKG-CEM-B14', depth: 1.1, layer: 'Burial Layer â€“ Mature Harappan Cemetery' },
        discoveredBy: admin._id,
        discoveredDate: new Date('2023-11-04'),
        tags: ['Carnelian', 'Jewelry', 'Burial', 'Trade', 'Beads'],
        storageLocation: 'ASI Headquarters, New Delhi â€“ Secure Vault V2',
        isPublic: true,
        createdBy: admin._id,
      },

      // DHOLAVIRA
      {
        name: 'Dholavira Indus Script Signboard Fragment',
        catalogNumber: 'DLV-ART-001',
        site: dholavira._id,
        category: 'Inscriptions',
        material: 'Gypsum inlaid on wood',
        estimatedAge: '2500â€“2000 BCE',
        era: 'Prehistoric',
        period: 'Mature Harappan',
        condition: 'Fragmentary',
        dimensions: { length: 37.0, width: 25.0, height: 2.5, weight: 950 },
        description: 'A large inscribed panel fragment bearing 10 Indus script characters inlaid with gypsum on a wooden background. Part of what is considered the world\'s earliest known public display inscription ("signboard"), originally measuring approximately 3 metres in length and displayed above the entrance of the northern gateway of the citadel.',
        significance: 'The Dholavira signboard represents the largest single Indus script inscription ever found and its placement above a gateway entrance suggests a public communicative function, fundamentally altering our understanding of Harappan literacy and public administration.',
        discoveryLocation: { gridReference: 'DLV-CIT-NGW', depth: 0.6, layer: 'Gateway Collapse Layer' },
        discoveredBy: lead1._id,
        discoveredDate: new Date('2023-04-19'),
        tags: ['Indus Script', 'Signboard', 'Gateway', 'Literacy', 'UNESCO'],
        storageLocation: 'ASI Conservation Lab, New Delhi â€“ Conservation Unit 1',
        isPublic: true,
        createdBy: admin._id,
      },
      {
        name: 'Chlorite Steatite Stamp Seal â€“ Bull Motif',
        catalogNumber: 'DLV-ART-002',
        site: dholavira._id,
        category: 'Inscriptions',
        material: 'Steatite',
        estimatedAge: '2600â€“2000 BCE',
        era: 'Prehistoric',
        period: 'Mature Harappan',
        condition: 'Excellent',
        dimensions: { length: 2.9, width: 2.9, height: 0.9, weight: 28 },
        description: 'Square steatite stamp seal with a naturalistic short-horned zebu bull (Bos indicus) in a standard lowered-head posture, and a line of 5 Indus script signs above. The reverse has a button-like boss for gripping. Found in the middle town marketplace zone.',
        significance: 'Zebu bull seals are one of the most iconic Indus artefact types, likely functioning as merchant identity tokens or administrative tools for marking goods and storage jars. The zebu bull may also have had religious significance as a symbol of strength and fertility.',
        discoveryLocation: { gridReference: 'DLV-MT-MKT3', depth: 1.2, layer: 'Layer 5 â€“ Marketplace Deposit' },
        discoveredBy: admin._id,
        discoveredDate: new Date('2023-07-28'),
        tags: ['Steatite Seal', 'Bull', 'Trade', 'Indus Script'],
        storageLocation: 'Gujarat State Museum, Ahmedabad â€“ Cabinet A12',
        isPublic: true,
        createdBy: admin._id,
      },
      {
        name: 'Gold Granulation Bangle',
        catalogNumber: 'DLV-ART-003',
        site: dholavira._id,
        category: 'Jewelry',
        material: 'Gold',
        estimatedAge: '2500â€“2000 BCE',
        era: 'Prehistoric',
        period: 'Mature Harappan',
        condition: 'Excellent',
        dimensions: { length: 7.2, width: 7.2, height: 0.8, weight: 32 },
        description: 'Circular gold bangle decorated with applied granulation technique â€” tiny spherical gold granules soldered onto the surface in geometric triangular patterns. Hollow construction with sheet gold. One of only three gold objects found in the Dholavira excavation, from a high-status residence context.',
        significance: 'The granulation technique on this bangle is among the earliest known examples in South Asia, demonstrating advanced goldworking skills and possibly connections to contemporary Near Eastern jewellery traditions.',
        discoveryLocation: { gridReference: 'DLV-MT-HS7', depth: 1.4, layer: 'Layer 4 â€“ High-Status Residential Floor' },
        discoveredBy: field1._id,
        discoveredDate: new Date('2023-09-12'),
        tags: ['Gold', 'Jewelry', 'Granulation', 'Craft', 'Elite'],
        storageLocation: 'ASI Headquarters, New Delhi â€“ Secure Vault V1',
        isPublic: true,
        createdBy: admin._id,
      },

      // KEELADI
      {
        name: 'Tamil-Brahmi Inscribed Pottery Sherd',
        catalogNumber: 'KLD-ART-001',
        site: keeladi._id,
        category: 'Pottery',
        material: 'Black and Red Ware (BRW)',
        estimatedAge: '500â€“300 BCE',
        era: 'Ancient',
        period: 'Early Sangam Era',
        condition: 'Good',
        dimensions: { length: 11.5, width: 8.2, height: 0.8, weight: 120 },
        description: 'A sherd of Black and Red Ware pottery with a graffito inscription in early Tamil-Brahmi script scratched after firing. The inscription reads "atan" (owner name). AMS radiocarbon dating of associated organic material returned a date of 580 BCE.',
        significance: 'This sherd pushes back the date of Tamil-Brahmi literacy to the 6th century BCE, confirming that literacy in ancient Tamil Nadu was contemporaneous with the Mauryan period and possibly predates it.',
        discoveryLocation: { gridReference: 'KLD-T4-PIT2', depth: 1.2, layer: 'Layer 6 â€“ Early Occupation' },
        discoveredBy: lead1._id,
        discoveredDate: new Date('2023-09-08'),
        tags: ['Tamil-Brahmi', 'Pottery', 'BRW', 'Epigraphy', 'Sangam'],
        storageLocation: 'Tamil Nadu State Dept. of Archaeology, Chennai â€“ Cabinet K3',
        isPublic: true,
        createdBy: lead1._id,
      },
      {
        name: 'Punch-Marked Copper Coin (Pandya Kingdom)',
        catalogNumber: 'KLD-ART-002',
        site: keeladi._id,
        category: 'Coins',
        material: 'Copper',
        estimatedAge: '300â€“100 BCE',
        era: 'Ancient',
        period: 'Sangam Era',
        condition: 'Fair',
        dimensions: { length: 1.8, width: 1.8, height: 0.2, weight: 3.5 },
        description: 'Small copper punch-marked coin with five symbols: a fish (Pandya royal symbol), a tree, an arched hill, a crescent, and a swastika-like symbol. Found within a foundation deposit under a wall in the northern residential quarter.',
        significance: 'Punch-marked coins bearing the fish symbol confirm this site\'s association with the Pandya kingdom. The fish symbol ("meen" in Tamil) is the royal emblem of the Pandya dynasty, providing strong numismatic evidence for political context.',
        discoveryLocation: { gridReference: 'KLD-T8-NQ3', depth: 0.9, layer: 'Layer 4 â€“ Late Sangam Occupation' },
        discoveredBy: viewer._id,
        discoveredDate: new Date('2023-10-15'),
        tags: ['Coin', 'Pandya', 'Punch-Marked', 'Numismatics', 'Trade'],
        storageLocation: 'Tamil Nadu State Dept. of Archaeology, Chennai â€“ Coin Cabinet 2',
        isPublic: true,
        createdBy: lead1._id,
      },
      {
        name: 'Gold Ear Ornament (Thodu)',
        catalogNumber: 'KLD-ART-003',
        site: keeladi._id,
        category: 'Jewelry',
        material: 'Gold',
        estimatedAge: '300â€“100 BCE',
        era: 'Ancient',
        period: 'Sangam Era',
        condition: 'Excellent',
        dimensions: { length: 2.4, width: 1.8, height: 0.6, weight: 5.8 },
        description: 'Crescent-shaped gold ear ornament ("thodu") with intricate filigree work and granulation. The outer arc carries a series of five tiny lotus-petal motifs. One of a pair found together in a compact clay-sealed pit, possibly a hoard or votive deposit. XRF analysis: 22 karat gold.',
        significance: 'The sophisticated filigree and granulation techniques indicate a mature goldsmithing tradition in Sangam-era Tamil Nadu, with strong parallels to jewellery described in Sangam literary texts such as the Purananuru.',
        discoveryLocation: { gridReference: 'KLD-T6-PIT4', depth: 1.0, layer: 'Layer 5 â€“ Hoard Deposit' },
        discoveredBy: lead1._id,
        discoveredDate: new Date('2023-11-20'),
        tags: ['Gold', 'Jewelry', 'Sangam', 'Thodu', 'Filigree'],
        storageLocation: 'Tamil Nadu State Dept. of Archaeology, Chennai â€“ Secure Safe S1',
        isPublic: true,
        createdBy: lead1._id,
      },
      {
        name: 'Terracotta Ring Well Section',
        catalogNumber: 'KLD-ART-004',
        site: keeladi._id,
        category: 'Architectural',
        material: 'Terracotta',
        estimatedAge: '300 BCE â€“ 300 CE',
        era: 'Ancient',
        period: 'Sangam Era',
        condition: 'Good',
        dimensions: { length: 30.0, width: 30.0, height: 22.0, weight: 6500 },
        description: 'Large thick-walled terracotta ring section, one of six such rings forming a soak well structure in the southeastern sector. Outer surface ribbed for mechanical interlocking. Several similar ring well structures have been identified at Keeladi, indicating a sophisticated urban water and waste management system.',
        significance: 'The presence of ring well structures at Keeladi provides irrefutable evidence of urban infrastructure and planning, placing Keeladi among the earliest Tamil urban centres.',
        discoveryLocation: { gridReference: 'KLD-T9-SE-W2', depth: 1.6, layer: 'Layer 5 â€“ Urban Infrastructure' },
        discoveredBy: field1._id,
        discoveredDate: new Date('2024-01-08'),
        tags: ['Architecture', 'Ring Well', 'Urban', 'Infrastructure', 'Water Management'],
        storageLocation: 'In-situ (partially conserved)',
        isPublic: true,
        createdBy: lead1._id,
      },

      // LOTHAL
      {
        name: 'Terracotta Game Board',
        catalogNumber: 'LTL-ART-001',
        site: lothal._id,
        category: 'Other',
        material: 'Terracotta',
        estimatedAge: '2400â€“1900 BCE',
        era: 'Prehistoric',
        period: 'Mature Harappan',
        condition: 'Good',
        dimensions: { length: 22.0, width: 18.0, height: 2.0, weight: 650 },
        description: 'Rectangular terracotta board with 8x7 grid of incised lines forming 56 playing squares. Two corner squares are marked with cross-hatch patterns. Associated with a small collection of terracotta conical game pieces found nearby.',
        significance: 'This game board is among the earliest evidence of board games in South Asia, suggesting leisure culture and abstract strategic thinking among Harappan urban populations.',
        discoveryLocation: { gridReference: 'LTL-LT-DOM5', depth: 1.0, layer: 'Domestic Layer 3' },
        discoveredBy: field1._id,
        discoveredDate: new Date('2023-05-14'),
        tags: ['Game', 'Board Game', 'Leisure', 'Terracotta', 'Urban Life'],
        storageLocation: 'ASI Site Museum, Lothal â€“ Display Cabinet 4',
        isPublic: true,
        createdBy: field1._id,
      },
      {
        name: 'Faience Bead Cylinder (Bead Factory)',
        catalogNumber: 'LTL-ART-002',
        site: lothal._id,
        category: 'Jewelry',
        material: 'Faience (silica glaze)',
        estimatedAge: '2400â€“1900 BCE',
        era: 'Prehistoric',
        period: 'Mature Harappan',
        condition: 'Good',
        dimensions: { length: 3.2, width: 1.2, height: 1.2, weight: 18 },
        description: 'Cylindrical faience (vitreous silica) bead with a longitudinal perforation and bright turquoise-blue glaze. Found in a group of 87 similar beads in the bead workshop, along with stone drills, raw faience nodules, and polishing stones.',
        significance: 'The Lothal bead factory is one of the most important craft production centres documented in the Indus Civilisation. Faience beads were exported as far as Mesopotamia, demonstrating Lothal\'s role as a hub in Bronze Age international trade networks.',
        discoveryLocation: { gridReference: 'LTL-BF-W1', depth: 0.8, layer: 'Workshop Layer 2 â€“ Bead Factory' },
        discoveredBy: field1._id,
        discoveredDate: new Date('2023-06-30'),
        tags: ['Faience', 'Bead', 'Trade', 'Workshop', 'Maritime'],
        storageLocation: 'ASI Site Museum, Lothal â€“ Display Cabinet 6',
        isPublic: true,
        createdBy: field1._id,
      },
      {
        name: 'Standardised Chert Weight (Cuboid)',
        catalogNumber: 'LTL-ART-003',
        site: lothal._id,
        category: 'Tools',
        material: 'Chert',
        estimatedAge: '2400â€“1900 BCE',
        era: 'Prehistoric',
        period: 'Mature Harappan',
        condition: 'Excellent',
        dimensions: { length: 2.1, width: 2.1, height: 2.1, weight: 53.5 },
        description: 'Perfect cuboid chert weight of the Harappan standardised weighing system, corresponding to 16 units in the binary-decimal series. The surface is highly polished with no visible toolmarks. Found in the warehouse complex near the dockyard.',
        significance: 'Harappan standardised weights are found from Afghanistan to Gujarat and represent the most sophisticated metrological system in the ancient world, enabling long-distance commercial transactions. Their uniformity is evidence of centralised administration.',
        discoveryLocation: { gridReference: 'LTL-WH-S3', depth: 0.7, layer: 'Warehouse Floor Level' },
        discoveredBy: field1._id,
        discoveredDate: new Date('2023-07-18'),
        tags: ['Weight', 'Trade', 'Standardisation', 'Commerce', 'Chert'],
        storageLocation: 'ASI Site Museum, Lothal â€“ Display Cabinet 8',
        isPublic: true,
        createdBy: field1._id,
      },

      // NALANDA
      {
        name: 'Gupta Period Bronze Buddha (Dhyana Mudra)',
        catalogNumber: 'NLD-ART-001',
        site: nalanda._id,
        category: 'Other',
        material: 'Bronze (copper-tin alloy)',
        estimatedAge: '5thâ€“6th century CE',
        era: 'Classical',
        period: 'Gupta Period',
        condition: 'Good',
        dimensions: { length: 18.0, width: 11.0, height: 28.0, weight: 4200 },
        description: 'Seated bronze Buddha in dhyana (meditation) mudra, cross-legged on a double-lotus throne. The figure displays the characteristic Gupta aesthetic: thin, clinging robe with incised folds, serene facial expression, ushnisha with flame finial, and elongated earlobes. Traces of gilding remain on the robe hem and throne.',
        significance: 'This statue epitomises the Gupta artistic canon, considered the golden age of Indian art. Nalanda bronze-casting workshops produced canonical images that were exported across Asia, influencing Buddhist artistic traditions from Southeast Asia to Japan.',
        discoveryLocation: { gridReference: 'NLD-V1B-SF3', depth: 0.45, layer: 'Vihara 1B Secondary Fill' },
        discoveredBy: lead2._id,
        discoveredDate: new Date('2024-02-20'),
        tags: ['Buddhist', 'Bronze', 'Gupta', 'Sculpture', 'Buddha'],
        storageLocation: 'Nalanda Archaeological Museum â€“ Cabinet B3',
        isPublic: true,
        createdBy: lead2._id,
      },
      {
        name: 'Terracotta Plaque â€“ Goddess Tara',
        catalogNumber: 'NLD-ART-002',
        site: nalanda._id,
        category: 'Other',
        material: 'Terracotta',
        estimatedAge: '8thâ€“9th century CE',
        era: 'Medieval',
        period: 'Pala Period',
        condition: 'Fair',
        dimensions: { length: 14.5, width: 9.0, height: 1.5, weight: 380 },
        description: 'Rectangular terracotta plaque with moulded image of the Bodhisattva Tara â€” right hand in vara mudra (boon-giving), left hand holding a half-open lotus. Flanked by two small attendant figures and a garland border. Mass-produced plaques like this were used as votive offerings by pilgrims.',
        significance: 'Pala-period terracotta plaques from Nalanda are distributed across Buddhist sites from Bengal to Southeast Asia. The Tara cult that flourished at Nalanda heavily influenced Tibetan and Vajrayana Buddhist iconography.',
        discoveryLocation: { gridReference: 'NLD-STP3-W3', depth: 0.3, layer: 'Surface Layer â€“ Stupa 3 Enclosure' },
        discoveredBy: lead2._id,
        discoveredDate: new Date('2024-03-15'),
        tags: ['Tara', 'Buddhist', 'Pala', 'Votive', 'Terracotta Plaque'],
        storageLocation: 'Nalanda Archaeological Museum â€“ Cabinet C5',
        isPublic: true,
        createdBy: lead2._id,
      },
      {
        name: 'Palm-Leaf Manuscript Fragment',
        catalogNumber: 'NLD-ART-003',
        site: nalanda._id,
        category: 'Organic Material',
        material: 'Palm leaf (Livistona sp.)',
        estimatedAge: '10thâ€“11th century CE',
        era: 'Medieval',
        period: 'Pala Period',
        condition: 'Fragmentary',
        dimensions: { length: 38.0, width: 5.5, height: 0.1, weight: 4 },
        description: 'Carbonised palm-leaf manuscript fragment with two lines of Siddham script text visible under multispectral imaging. Text appears to be a portion of the Prajnaparamita (Perfection of Wisdom) sutra. Found sealed in a secondary deposit beneath a stupa votive cell, preserved from the conflagration that destroyed Nalanda in 1193 CE.',
        significance: 'This fragment is one of extremely few surviving physical remnants of Nalanda\'s legendary library, which is recorded by Chinese pilgrim Xuanzang as containing millions of manuscripts. The fragment provides direct material evidence of Nalanda\'s role as the centre of Mahayana Buddhist scriptural tradition.',
        discoveryLocation: { gridReference: 'NLD-STP5-VC7', depth: 0.6, layer: 'Votive Cell Sealed Fill' },
        discoveredBy: lead2._id,
        discoveredDate: new Date('2024-04-02'),
        tags: ['Manuscript', 'Palm Leaf', 'Siddham Script', 'Buddhism', 'Library'],
        storageLocation: 'Nalanda Archaeological Museum â€“ Conservation Lab, Cold Store 1',
        isPublic: true,
        createdBy: lead2._id,
      },

      // HAMPI
      {
        name: 'Vijayanagara Bronze Virabhadra Statuette',
        catalogNumber: 'HMP-ART-001',
        site: hampi._id,
        category: 'Other',
        material: 'Bronze (Panchaloha)',
        estimatedAge: '14thâ€“16th century CE',
        era: 'Medieval',
        period: 'Vijayanagara Empire',
        condition: 'Good',
        dimensions: { length: 12.0, width: 8.5, height: 22.0, weight: 1850 },
        description: 'Processional bronze statuette of Virabhadra â€” the ferocious warrior form of Shiva â€” depicted in alidha (warrior stance) with ten arms holding weapons. Eyes are inlaid with silver dots. Flat base with tenon for mounting on a processional throne. Panchaloha (five-metal alloy) casting of high quality.',
        significance: 'Virabhadra is closely associated with Hampi as the city\'s tutelary deity. This processional image would have been carried in festival processions, reflecting the ceremonial life of the Vijayanagara court.',
        discoveryLocation: { gridReference: 'HMP-RE-TEMP4', depth: 0.35, layer: 'Temple Collapse Layer' },
        discoveredBy: admin._id,
        discoveredDate: new Date('2023-12-10'),
        tags: ['Vijayanagara', 'Bronze', 'Shiva', 'Virabhadra', 'Medieval'],
        storageLocation: 'Archaeological Museum, Hampi â€“ Gallery 2',
        isPublic: true,
        createdBy: admin._id,
      },
      {
        name: 'Vijayanagara Gold Fanam Coin Hoard',
        catalogNumber: 'HMP-ART-002',
        site: hampi._id,
        category: 'Coins',
        material: 'Gold',
        estimatedAge: '15th century CE',
        era: 'Medieval',
        period: 'Vijayanagara Empire',
        condition: 'Excellent',
        dimensions: { length: 0.9, width: 0.9, height: 0.1, weight: 0.38 },
        description: 'Group of 47 gold fanam coins found within a small earthenware pot (coin hoard) sealed beneath a collapsed wall in the market bazaar area. Obverse: standing Vishnu (Venkatesha). Reverse: Kannada script legend "Sri Virupaksha".',
        significance: 'Fanam coins were the standard small-denomination gold currency of the Vijayanagara Empire. Their presence in the market bazaar confirms the site\'s role as a commercial zone. The legend "Sri Virupaksha" reaffirms royal patronage of the deity Virupaksha.',
        discoveryLocation: { gridReference: 'HMP-MKT-B7', depth: 0.55, layer: 'Market Bazaar Floor Level' },
        discoveredBy: viewer._id,
        discoveredDate: new Date('2024-01-22'),
        tags: ['Gold Coin', 'Fanam', 'Vijayanagara', 'Hoard', 'Trade'],
        storageLocation: 'Archaeological Museum, Hampi â€“ Coin Gallery, Case 4',
        isPublic: true,
        createdBy: admin._id,
      },

      // SANCHI
      {
        name: 'Ashokan Pillar Fragment with Brahmi Inscription',
        catalogNumber: 'SCH-ART-001',
        site: sanchi._id,
        category: 'Inscriptions',
        material: 'Chunar Sandstone',
        estimatedAge: '3rd century BCE (Mauryan)',
        era: 'Ancient',
        period: 'Mauryan Period',
        condition: 'Good',
        dimensions: { length: 42.0, width: 28.0, height: 18.0, weight: 38000 },
        description: 'Polished Chunar sandstone column fragment bearing a three-line Brahmi inscription recording a donation by a guild of ivory workers (dantakara-seni) for the eastern gateway balustrade of the Great Stupa. The mirror-like polish is typical of the Ashokan workshop at Chunar.',
        significance: 'This inscription provides direct evidence for the range of social groups â€” merchant guilds, craftspeople â€” who contributed to Buddhist monument construction at Sanchi, demonstrating that monastic endowment was a broad community practice.',
        discoveryLocation: { gridReference: 'SCH-STP1-EG', depth: 0.25, layer: 'Torana Collapse Debris' },
        discoveredBy: lead2._id,
        discoveredDate: new Date('2024-01-30'),
        tags: ['Brahmi', 'Ashoka', 'Donation Inscription', 'Stupa', 'Sandstone'],
        storageLocation: 'Sanchi Archaeological Museum â€“ Gallery 1',
        isPublic: true,
        createdBy: lead2._id,
      },
      {
        name: 'Ivory Railing Medallion â€“ Yakshi Figure',
        catalogNumber: 'SCH-ART-002',
        site: sanchi._id,
        category: 'Other',
        material: 'Ivory',
        estimatedAge: '1st century BCE â€“ 1st century CE',
        era: 'Ancient',
        period: 'Shungaâ€“Satavahana Period',
        condition: 'Fair',
        dimensions: { length: 9.5, width: 9.5, height: 1.8, weight: 180 },
        description: 'Circular ivory medallion carved in high relief with a Yakshi (tree-spirit/nature deity) in the classic three-bend (tribhanga) posture, grasping a mango branch above, flanked by symmetrical floral scrollwork. Traces of red and yellow pigment remain in the deeper carved recesses.',
        significance: 'The Yakshi motif at Sanchi is among the most iconic images of early Indian art, representing the assimilation of pre-Vedic fertility and nature-worship traditions into the Buddhist architectural programme. The tribhanga posture became the standard pose for female divine figures across all subsequent Indian art traditions.',
        discoveryLocation: { gridReference: 'SCH-STP1-INR', depth: 0.4, layer: 'Inner Railing Fill' },
        discoveredBy: lead2._id,
        discoveredDate: new Date('2024-02-18'),
        tags: ['Ivory', 'Yakshi', 'Buddhist Art', 'Shunga', 'Sculpture'],
        storageLocation: 'Sanchi Archaeological Museum â€“ Gallery 2, Cabinet 3',
        isPublic: true,
        createdBy: lead2._id,
      },

      // AJANTA
      {
        name: 'Painted Plaster Fragment â€“ Mahajanaka Jataka',
        catalogNumber: 'AJT-ART-001',
        site: ajanta._id,
        category: 'Other',
        material: 'Lime plaster with mineral pigments',
        estimatedAge: '5th century CE',
        era: 'Ancient',
        period: 'Vakataka Period',
        condition: 'Fragmentary',
        dimensions: { length: 38.0, width: 26.0, height: 2.5, weight: 2100 },
        description: 'Fragment of painted plaster panel from Cave 1, Ajanta, depicting a scene from the Mahajanaka Jataka. The composition shows a seated royal figure in a lush palace setting. Pigments identified include lapis lazuli (blue), red ochre, lamp black, and white lime. Multispectral imaging has revealed a detailed underdrawing beneath the final composition.',
        significance: 'The Ajanta paintings are considered among the greatest examples of pre-modern Indian art. This fragment\'s underdrawing layer provides unprecedented insight into the Ajanta artists\' compositional process.',
        discoveryLocation: { gridReference: 'AJT-CV1-WW-S4', depth: 0.0, layer: 'Surface (fallen fragment)' },
        discoveredBy: admin._id,
        discoveredDate: new Date('2024-06-10'),
        tags: ['Ajanta', 'Painting', 'Jataka', 'Buddhist Art', 'Conservation'],
        storageLocation: 'ASI Conservation Lab, Aurangabad â€“ Cold Storage Unit 2',
        isPublic: true,
        createdBy: admin._id,
      },
    ]);

    console.log(`âœ… Created ${artifacts.length} artifacts.`);

    // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    // FIELD LOGS
    // â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    console.log('ðŸ“‹ Creating field logs...');

    const logs = await ExcavationLog.insertMany([
      // RAKHIGARHI logs
      {
        site: rakhigarhi._id,
        title: 'Trench RKG-T7: Mature Harappan Floor Level Exposed',
        date: new Date('2023-03-14'),
        content: '<p>Team of 12 workers under supervision of Dr. Rajesh Sharma and Dr. Anand Joshi. Excavation of Trench T7 (5x5m) continued from depth 1.8m to 2.1m below surface. A compact burnt mud-brick floor level was uncovered â€” a major milestone. The floor shows evidence of in-situ burning, with a small circular hearth at its centre (40cm diameter), filled with ash and charred animal bones.</p><p>Five terracotta pottery sherds (Black and Red Ware and plain Red Ware) recovered from the floor surface. Three ground stone tools (grinding stones) found in-situ near the northern wall stub. The unicorn seal (RKG-ART-001) was discovered at 2.3m depth beneath this floor.</p>',
        weather: { condition: 'Sunny', temperature: 26, humidity: 45, notes: 'Clear skies, moderate wind. Excellent working conditions.' },
        teamPresent: [
          { user: admin._id, role: 'Principal Investigator' },
          { user: field1._id, role: 'Trench Supervisor' },
        ],
        depth: { from: 1.8, to: 2.3, layer: 'Layer 4 â€“ Mature Harappan Occupation', description: 'Compact mud-brick debris and floor levels' },
        findings: 'Mature Harappan floor level with fire pit, BRW pottery, ground stones. Unicorn stamp seal (RKG-ART-001) recovered.',
        createdBy: admin._id,
        isPublic: true,
      },
      {
        site: rakhigarhi._id,
        title: 'Cemetery Excavation: Burial B-14 with Carnelian Necklace',
        date: new Date('2023-11-03'),
        content: '<p>Formal burial B-14 fully excavated today. Primary inhumation in extended supine position (head to north, feet to south), contained within a purpose-cut pit. Skeletal remains of an adult individual in moderately good preservation.</p><p>Grave goods include the intact carnelian bead necklace (RKG-ART-004) still in situ on the chest area, a terracotta pot placed at the feet, and three small conical terracotta game pieces near the right hand. Soil samples collected from around skull for botanical analysis, and bone samples for AMS radiocarbon dating sent to Beta Analytic laboratory.</p>',
        weather: { condition: 'Cloudy', temperature: 22, humidity: 60, notes: 'Overcast but no rain. Comfortable temperature for detailed excavation work.' },
        teamPresent: [
          { user: admin._id, role: 'Principal Investigator' },
          { user: field1._id, role: 'Physical Anthropologist' },
          { user: lead2._id, role: 'Environmental Sampling' },
        ],
        depth: { from: 0.8, to: 1.2, layer: 'Burial Layer â€“ Mature Harappan Cemetery', description: 'Primary inhumation burial pit' },
        findings: 'Complete burial with carnelian necklace (RKG-ART-004), terracotta pot, game pieces. Bone and soil samples taken for laboratory analysis.',
        createdBy: admin._id,
        isPublic: true,
      },
      {
        site: rakhigarhi._id,
        title: 'Fire Altar Complex Documentation â€” Mound 1',
        date: new Date('2024-01-18'),
        content: '<p>Resumed work on the fire altar complex in Mound 1. Seven successive fire altars (aligned NWâ€“SE) are now documented, each comprising a rectangular mud-brick basin (approx. 60cm x 40cm) filled with fine ash, charred grain, and animal bones. The altars show evidence of repeated cleaning and replastering â€” indicating periodic ritual use over an extended period.</p><p>Thermoluminescence (TL) samples collected from two altars for dating. Pollen samples taken from sealed ash layers for environmental reconstruction. GPR survey of adjacent area (10x10m) completed to identify further structures â€” preliminary results suggest 3â€“4 additional structures to the northeast.</p>',
        weather: { condition: 'Sunny', temperature: 18, humidity: 38, notes: 'January cold wave subsiding. Morning fog cleared by 10:30am.' },
        teamPresent: [
          { user: admin._id, role: 'Principal Investigator' },
          { user: lead2._id, role: 'Environmental Specialist' },
          { user: field1._id, role: 'Trench Supervisor' },
        ],
        depth: { from: 1.2, to: 1.8, layer: 'Altar Layer â€“ Mature Harappan', description: 'Multiple fire altars in succession' },
        findings: 'Seven fire altars documented. TL samples collected. Pollen samples taken. GPR survey completed identifying possible further structures.',
        createdBy: admin._id,
        isPublic: true,
      },

      // DHOLAVIRA logs
      {
        site: dholavira._id,
        title: 'Northern Gateway Signboard Context Confirmed',
        date: new Date('2023-04-18'),
        content: '<p>Today marks one of the most significant breakthroughs of the Dholavira project. Dr. Priya Natarajan led the careful cleaning and documentation of a collapse deposit at the Northern Gateway of the Citadel. Beneath a thick layer of brick debris was found a wooden plank fragment with intact gypsum-inlaid Indus script characters (DLV-ART-001).</p><p>The fragment carries 10 clearly legible script signs. The original discovery of this signboard in the 1990s established it as the world\'s earliest known public inscription. This season\'s re-excavation has produced a new fragment not previously recovered. Conservation team immediately treated the wooden fragment with PEG consolidant. RTI imaging and 3D photogrammetry completed before lifting.</p>',
        weather: { condition: 'Hot', temperature: 38, humidity: 22, notes: 'Extreme heat in Rann of Kutch. Work suspended 12:30â€“15:30. All team members required to hydrate regularly.' },
        teamPresent: [
          { user: admin._id, role: 'Principal Investigator' },
          { user: lead1._id, role: 'Epigraphy Specialist' },
          { user: field1._id, role: 'Conservation Supervisor' },
        ],
        depth: { from: 0.4, to: 0.7, layer: 'Gateway Collapse Layer', description: 'Post-abandonment collapse of northern gateway structure' },
        findings: 'New signboard fragment (DLV-ART-001) recovered with 10 Indus script characters. PEG conservation treatment applied immediately.',
        createdBy: admin._id,
        isPublic: true,
      },
      {
        site: dholavira._id,
        title: 'Reservoir System Survey â€” Tanks 3 and 4',
        date: new Date('2023-07-05'),
        content: '<p>Full survey of Reservoir 3 (northern rock-cut reservoir) and Reservoir 4 (western reservoir) completed by Dr. Anand Joshi\'s team. Both reservoirs are cut into natural sandstone bedrock and fed by channels from the surrounding topography. Reservoir 3 (52m x 16m x 7m) retains its channel inlet in excellent condition; a mud-plastered settling tank precedes the main reservoir.</p><p>Cleaning of silt from Reservoir 3 base yielded 12 pottery sherds, a copper needle, and a carnelian bead. 3D laser scan of both reservoirs completed for volume calculation. GPR survey along the channel leading to Reservoir 4 identified a possible secondary branch channel not previously mapped.</p>',
        weather: { condition: 'Hot', temperature: 41, humidity: 18, notes: 'Peak summer in Kutch. Mandatory shade breaks every 45 minutes.' },
        teamPresent: [
          { user: field1._id, role: 'Field Supervisor' },
          { user: lead2._id, role: 'Environmental Analyst' },
        ],
        depth: { from: 0.0, to: 7.0, layer: 'Reservoir Silt Fill', description: 'Post-abandonment silt accumulation in reservoir basin' },
        findings: 'Survey and 3D scan of Reservoirs 3 and 4 completed. New channel branch identified by GPR. Minor finds: pottery, copper needle, carnelian bead.',
        createdBy: field1._id,
        isPublic: true,
      },
      {
        site: dholavira._id,
        title: 'Gold Bangle Conservation and XRF Analysis',
        date: new Date('2023-09-13'),
        content: '<p>The gold granulation bangle (DLV-ART-003) recovered yesterday from high-status residential Unit HS-7 was subjected to portable XRF (pXRF) analysis today in the field laboratory. Results confirm: gold (Au) 89.2%, silver (Ag) 6.3%, copper (Cu) 4.5% â€” indicating a pale gold alloy typical of Harappan period jewellery from Gujarat.</p><p>The granulation technique â€” applying tiny gold spheres to the surface â€” is among the earliest dated examples in South Asia. Conservation: surface cleaned with distilled water, treated with Paraloid B-72 consolidant at 2% in acetone. High-resolution photography (macro and RTI) completed. The bangle is now in secure storage awaiting transport to ASI headquarters.</p>',
        weather: { condition: 'Hot', temperature: 36, humidity: 25, notes: 'Hot but manageable. Field laboratory maintained at 24Â°C for XRF analysis.' },
        teamPresent: [
          { user: field1._id, role: 'Lead Conservator' },
          { user: admin._id, role: 'Principal Investigator' },
        ],
        depth: { from: 1.4, to: 1.4, layer: 'Layer 4 â€“ High-Status Residential Floor', description: 'In-situ find from residential floor' },
        findings: 'Gold bangle (DLV-ART-003) pXRF analysis: 89.2% Au, 6.3% Ag, 4.5% Cu. Conservation treatment applied. Macro photography and RTI completed.',
        createdBy: field1._id,
        isPublic: true,
      },

      // KEELADI logs
      {
        site: keeladi._id,
        title: 'Tamil-Brahmi Sherd Discovery â€” Trench T4',
        date: new Date('2023-09-07'),
        content: '<p>Remarkable discovery by Dr. Priya Natarajan\'s team in Trench T4. During fine-sieving of pit deposit PIT-2, a BRW pottery sherd with a clearly visible graffito inscription in early Tamil-Brahmi was recovered. The inscription, reading "atan" (owner/name), is scratched into the exterior vessel surface after firing with a sharp implement.</p><p>The sherd was recovered from a sealed pit deposit containing organic material (charred plant remains) that will allow AMS radiocarbon dating. Based on the ceramic typology and stratigraphic position (Layer 6, the earliest occupation layer), we expect a date of 600â€“400 BCE â€” potentially pushing back Tamil literacy by several centuries beyond previous consensus.</p>',
        weather: { condition: 'Cloudy', temperature: 31, humidity: 75, notes: 'Pre-monsoon humidity. Work continued with tent cover over Trench T4 to protect the inscription context.' },
        teamPresent: [
          { user: lead1._id, role: 'Field Director and Epigrapher' },
          { user: field1._id, role: 'Trench Supervisor' },
        ],
        depth: { from: 1.0, to: 1.3, layer: 'Layer 6 â€“ Earliest Occupation Pit', description: 'Early Sangam-era pit deposit' },
        findings: 'Tamil-Brahmi inscribed BRW sherd (KLD-ART-001) recovered from pit PIT-2. Organic material collected for AMS radiocarbon dating.',
        createdBy: lead1._id,
        isPublic: true,
      },
      {
        site: keeladi._id,
        title: 'Ring Well Structure Fully Excavated â€” Southern Sector',
        date: new Date('2024-01-07'),
        content: '<p>Excavation of ring-well structure RW-2 in the southeastern sector is complete. The structure consists of 6 interlocking terracotta rings (each approx. 22cm high, 30cm external diameter), creating a soak-well approximately 1.32m deep from the original floor level. The well is partially silted with a mix of domestic refuse including pottery sherds, animal bone fragments, and charred seeds.</p><p>A total of 4 complete ring well structures have now been documented at Keeladi across different excavation areas, confirming a city-wide sanitation and water management system. Soil samples from the silt fill sent to Birbal Sahni Institute for palaeobotanical analysis.</p>',
        weather: { condition: 'Sunny', temperature: 27, humidity: 58, notes: 'Post-northeast monsoon dry spell. Ground still slightly moist but workable.' },
        teamPresent: [
          { user: lead1._id, role: 'Field Director' },
          { user: field1._id, role: 'Trench Supervisor' },
          { user: lead2._id, role: 'Environmental Sampling' },
        ],
        depth: { from: 0.5, to: 1.8, layer: 'Urban Infrastructure Layer', description: 'Ring well structure in domestic occupation zone' },
        findings: 'Ring well RW-2 fully documented. 68 pottery sherds, bone fragments, charred seeds recovered. Palaeobotanical samples sent to BSIP Lucknow.',
        createdBy: lead1._id,
        isPublic: true,
      },
      {
        site: keeladi._id,
        title: 'Gold Thodu Ornaments Recovered from Sealed Pit',
        date: new Date('2023-11-19'),
        content: '<p>An exceptional discovery today in Trench T6. At 1.0m depth, field team encountered a small, tightly packed clay-sealed pit (PIT-4, 28cm diameter, 18cm deep). Careful excavation revealed a pair of gold ear ornaments (thodu) in pristine condition â€” still retaining their original spring-catch attachment mechanism.</p><p>The ornaments (KLD-ART-003) are crescent-shaped with exquisite filigree and granulation work. They were packed in close contact within the pit, with traces of decayed organic material (possibly a textile wrapping). pXRF analysis in the field showed gold purity of approximately 22 karat (91.7% gold). Objects transferred to the Chennai laboratory for detailed study.</p>',
        weather: { condition: 'Sunny', temperature: 29, humidity: 62, notes: 'Clear conditions â€” unusual find warranted extended afternoon session.' },
        teamPresent: [
          { user: lead1._id, role: 'Field Director' },
          { user: field1._id, role: 'Trench Supervisor' },
          { user: viewer._id, role: 'Gold Artefact Consultant' },
        ],
        depth: { from: 0.85, to: 1.05, layer: 'Layer 5 â€“ Hoard Pit', description: 'Intentional votive/hoard deposit in sealed pit' },
        findings: 'Pair of gold thodu ear ornaments (KLD-ART-003) recovered from sealed pit. XRF: 22 karat gold. Objects transferred to Chennai lab.',
        createdBy: lead1._id,
        isPublic: true,
      },
      {
        site: keeladi._id,
        title: 'Pandya Coin Hoard Identified â€” Northern Residential Quarter',
        date: new Date('2023-10-14'),
        content: '<p>Dr. Vikram Mehta (numismatic consultant) joined the team today for the examination of coin finds from Trench T8, northern residential quarter. A total of 8 punch-marked copper coins have been recovered from Layer 4 across a 2x2m area â€” suggesting a small hoard or a series of individual losses from the same context.</p><p>Dr. Mehta\'s preliminary identification: 5 coins bear the Pandya fish emblem with secondary symbols. Two coins appear to have Satavahana symbols. One coin is worn beyond identification. This is strong numismatic evidence for Keeladi\'s location within the Pandya political sphere and for commercial activity with Satavahana-controlled territories to the north.</p>',
        weather: { condition: 'Sunny', temperature: 30, humidity: 65, notes: 'Warm October day. Afternoon work conducted under shade canopy.' },
        teamPresent: [
          { user: lead1._id, role: 'Field Director' },
          { user: viewer._id, role: 'Numismatic Consultant' },
          { user: field1._id, role: 'Trench Supervisor' },
        ],
        depth: { from: 0.7, to: 1.0, layer: 'Layer 4 â€“ Late Sangam Occupation', description: 'Residential occupation layer with coin finds' },
        findings: '8 punch-marked copper coins (including KLD-ART-002). 5 Pandya fish-symbol coins, 2 probable Satavahana, 1 unidentified. Commercial evidence confirmed.',
        createdBy: lead1._id,
        isPublic: true,
      },

      // NALANDA logs
      {
        site: nalanda._id,
        title: 'Vihara 1B Excavation: Gupta Bronze Buddha Discovered',
        date: new Date('2024-02-19'),
        content: '<p>Excavation of secondary fill deposits in Vihara 1B is continuing under Dr. Sunita Deshmukh\'s direction. Today at 0.45m depth, the team encountered a compact clay fill pocket that yielded the Gupta-period seated bronze Buddha (NLD-ART-001).</p><p>The figure was found lying on its right side, apparently toppled from a now-missing base. The bronze retains traces of gilding on the robe. Iconographic assessment by Dr. Vikram Mehta confirms a 5thâ€“6th century CE date based on the robe treatment, ushnisha form, and lotus throne design. Full photogrammetric recording and XRF elemental analysis completed. Figure secured in the site safe for transport to the Nalanda Museum conservation lab.</p>',
        weather: { condition: 'Cold', temperature: 12, humidity: 55, notes: 'February morning cold. Work started at 9am after ground frost cleared.' },
        teamPresent: [
          { user: lead2._id, role: 'Site Director' },
          { user: viewer._id, role: 'Iconographic Consultant' },
          { user: field1._id, role: 'Recording Officer' },
        ],
        depth: { from: 0.3, to: 0.6, layer: 'Vihara Secondary Fill', description: 'Post-abandonment fill within monastic cell block' },
        findings: 'Gupta period seated bronze Buddha (NLD-ART-001) recovered from secondary fill. Gilding traces present. Photogrammetry and XRF completed.',
        createdBy: lead2._id,
        isPublic: true,
      },
      {
        site: nalanda._id,
        title: 'Palm Leaf Manuscript Fragments Recovered â€” Stupa 5',
        date: new Date('2024-04-01'),
        content: '<p>Extraordinary discovery in the votive cell zone of Stupa 5 today. At 0.6m depth in a sealed clay-capped deposit within cell VC-7, Dr. Sunita Deshmukh\'s team encountered carbonised organic material with distinctive flat-leaf morphology. Microscopic examination confirms this is palm leaf (Livistona sp.) manuscript material.</p><p>The fragment (NLD-ART-003) shows two lines of Siddham script visible under multispectral imaging in the field. Text identified by Dr. Vikram Mehta as a portion of the Prajnaparamita sutra. The palm leaves were sealed in the cell before the 1193 CE conflagration and carbonised but preserved by the clay seal above. This is one of very few surviving material remnants of Nalanda\'s legendary library.</p>',
        weather: { condition: 'Hot', temperature: 34, humidity: 50, notes: 'April heat building. Fans set up in field lab for manuscript examination. All manuscript handling under climate control.' },
        teamPresent: [
          { user: lead2._id, role: 'Site Director' },
          { user: viewer._id, role: 'Manuscript Consultant' },
        ],
        depth: { from: 0.55, to: 0.65, layer: 'Votive Cell Sealed Fill', description: 'Clay-sealed votive cell beneath Stupa 5' },
        findings: 'Palm-leaf manuscript fragment (NLD-ART-003) with Prajnaparamita text identified. Conservation treatment applied. Sent to Lucknow for palaeographic analysis.',
        createdBy: lead2._id,
        isPublic: true,
      },

      // HAMPI logs
      {
        site: hampi._id,
        title: 'Market Bazaar Zone Documentation â€” Southern Extension',
        date: new Date('2023-10-04'),
        content: '<p>Survey team extended the systematic surface documentation of the southern bazaar zone â€” an elongated market street approximately 750m long running east-west, flanked by regular stone platform plinths (each approx. 6m x 4m) for market stalls. Today\'s work covered the western 200m section.</p><p>Forty-three merchant platform bases documented, measured, and photographed. Several platforms retain in-situ stone pillar bases. Two of these retain partially legible Kannada inscriptions recording merchant guild dedications â€” one mentions the "Ayyavole" merchant guild, famous across medieval South and Southeast Asia. The gold fanam coin hoard (HMP-ART-002) was recovered today from a pot sealed beneath collapsed wall debris in Bazaar Unit B7.</p>',
        weather: { condition: 'Sunny', temperature: 32, humidity: 48, notes: 'October dry season beginning. Ideal survey conditions.' },
        teamPresent: [
          { user: admin._id, role: 'Principal Investigator' },
          { user: lead1._id, role: 'Epigraphy Lead' },
          { user: field1._id, role: 'GIS Survey Lead' },
          { user: viewer._id, role: 'Numismatic Consultant' },
        ],
        depth: { from: 0.0, to: 0.6, layer: 'Market Bazaar Surface and Sub-Surface', description: 'Medieval Vijayanagara market street and platform bases' },
        findings: '43 market platforms documented. 2 Kannada guild inscriptions recorded. Gold fanam coin hoard (HMP-ART-002) of 47 coins recovered.',
        createdBy: admin._id,
        isPublic: true,
      },
      {
        site: hampi._id,
        title: 'Royal Enclosure Elephant Stables Survey',
        date: new Date('2024-02-14'),
        content: '<p>Detailed architectural survey of the Elephant Stables (Gajashala) within the Royal Enclosure completed today. The structure consists of 11 chambers in a single row, each originally surmounted by a different domed or vaulted ceiling (8 survive intact). Each chamber is approx. 15m x 15m with pointed arched entrance. The structure is a masterpiece of Vijayanagara Indo-Islamic architecture, combining pointed arches with Hindu sculptural ornamentation.</p><p>Ground survey identified 3 previously unrecorded foundation walls to the north of the Stables â€” possibly stabling yards or fodder stores. GPR profiles scheduled for the next session. All 11 chambers measured, photographed, and photogrammetrically recorded at 1mm resolution.</p>',
        weather: { condition: 'Sunny', temperature: 28, humidity: 42, notes: 'February is ideal season in Hampi. Team of 8 surveyors worked efficiently in mild conditions.' },
        teamPresent: [
          { user: admin._id, role: 'Principal Investigator' },
          { user: field1._id, role: 'Architectural Survey Lead' },
        ],
        depth: { from: 0.0, to: 0.4, layer: 'Surface and Near-Surface', description: 'Architectural survey and sub-surface prospection' },
        findings: 'Elephant Stables fully recorded at 1mm resolution. 3 unrecorded foundation walls identified north of Stables. GPR survey scheduled.',
        createdBy: admin._id,
        isPublic: true,
      },

      // SANCHI logs
      {
        site: sanchi._id,
        title: 'GPR Survey Reveals Buried Settlement South of Great Stupa',
        date: new Date('2024-01-05'),
        content: '<p>First field day of the 2024 season at Sanchi. Dr. Sunita Deshmukh and Dr. Anand Joshi conducted a 50x50m GPR survey of the area south of the Great Stupa. The results are extraordinary: a dense field of sub-surface anomalies at 0.4â€“1.2m depth indicates the presence of a large buried settlement with regular structural alignments (walls, floors, possible courtyards) extending at least 30m south of the known monument boundary.</p><p>This discovery significantly expands our understanding of the size and complexity of the lay community that supported the Sanchi Buddhist establishment. Finds from the topsoil: 18 pottery sherds (NBP, Red Ware, Stamped Grey Ware) and 1 terracotta human figurine fragment.</p>',
        weather: { condition: 'Cold', temperature: 9, humidity: 50, notes: 'Winter cold at Sanchi plateau. Morning temperature 6Â°C. Afternoon warmed to 18Â°C.' },
        teamPresent: [
          { user: lead2._id, role: 'Principal Investigator' },
          { user: field1._id, role: 'GPR Operator' },
        ],
        depth: { from: 0.0, to: 1.2, layer: 'GPR Survey Depth Range', description: 'Non-invasive sub-surface detection survey' },
        findings: 'Major buried settlement detected south of Great Stupa. NBP pottery, terracotta figurine fragment from topsoil survey. Test trenches planned for next season.',
        createdBy: lead2._id,
        isPublic: true,
      },
      {
        site: sanchi._id,
        title: 'Brahmi Inscription Documentation â€” Eastern Gateway',
        date: new Date('2024-02-08'),
        content: '<p>Dr. Sunita Deshmukh and visiting epigrapher Dr. Priya Natarajan completed RTI (Reflectance Transformation Imaging) documentation of all donative Brahmi inscriptions on the Eastern Gateway (Eastern Torana) of the Great Stupa. 47 individual donor inscriptions recorded on the four crossbars and two uprights of the gateway â€” the most densely inscribed monument structure at Sanchi.</p><p>The Chunar sandstone pillar fragment (SCH-ART-001) was identified during clearing of debris at the gateway base and removed for conservation. New inscriptions identified today include a donation by "Avadhika devi, wife of a minister of king Satakarni" â€” providing a prosopographic link to the Satavahana dynasty.</p>',
        weather: { condition: 'Cold', temperature: 14, humidity: 42, notes: 'February sunshine makes RTI photography difficult in afternoon. Morning sessions yielded best results.' },
        teamPresent: [
          { user: lead2._id, role: 'Principal Investigator' },
          { user: lead1._id, role: 'Visiting Epigrapher' },
        ],
        depth: { from: 0.0, to: 0.3, layer: 'Gateway Base and Torana Surface', description: 'Architectural documentation and epigraphy' },
        findings: '47 Brahmi donor inscriptions documented by RTI. Pillar fragment (SCH-ART-001) recovered. New Satavahana-era royal family inscription identified.',
        createdBy: lead2._id,
        isPublic: true,
      },

      // LOTHAL logs
      {
        site: lothal._id,
        title: 'Bead Factory Workshop Floor Cleared',
        date: new Date('2023-06-29'),
        content: '<p>Second full week of bead workshop excavation at Lothal. Dr. Anand Joshi supervised complete clearance of the workshop floor (approx. 6m x 4m). The floor surface (rammed earth, well-compacted) is intact across 80% of its extent. In-situ equipment: 4 stone drills (chert), 2 copper drill bits (worn), 3 polishing slabs (sandstone), a large flat hearth stone with vitrified deposits.</p><p>Debris from the floor includes approximately 200 faience nodules in various stages of production, 87 finished faience beads (LTL-ART-002 group), 34 carnelian blanks, and 12 perforated but unpolished carnelian beads. This assemblage provides a complete chaÃ®ne opÃ©ratoire for Harappan bead production â€” from raw material to finished product â€” at a single findspot.</p>',
        weather: { condition: 'Hot', temperature: 39, humidity: 70, notes: 'Pre-monsoon heat and humidity in Gujarat. Site tented. Cold water distributed hourly.' },
        teamPresent: [
          { user: field1._id, role: 'Field Director' },
          { user: lead2._id, role: 'Environmental Sampling' },
        ],
        depth: { from: 0.6, to: 0.9, layer: 'Workshop Layer 2 â€“ Bead Factory Floor', description: 'In-situ bead workshop floor with complete manufacturing assemblage' },
        findings: 'Complete bead manufacturing assemblage. 87 faience beads (LTL-ART-002 group), carnelian blanks, drills, polishing slabs. Complete chaÃ®ne opÃ©ratoire documented.',
        createdBy: field1._id,
        isPublic: true,
      },
      {
        site: lothal._id,
        title: 'Dockyard West Wall Structural Survey',
        date: new Date('2023-08-20'),
        content: '<p>Structural survey of the western retaining wall of the Lothal dockyard is now complete. The dockyard (approx. 218m x 37m, depth 4.15m) is constructed of kiln-fired brick with a precise proportional brick system (ratio 1:2:4). The west wall (1.2m wide at base) is constructed in a herringbone brick pattern â€” a structural technique providing exceptional resistance to hydraulic pressure.</p><p>The sluice gate channel at the south end is well preserved, with the sliding-groove mechanism for the wooden gate still visible as a rectangular slot in the brick. Tidal water management at the dockyard allowed ships to enter at high tide and be worked at low tide â€” a remarkable hydraulic engineering solution. 3D photogrammetric model of the entire dockyard completed at 0.8mm resolution.</p>',
        weather: { condition: 'Cloudy', temperature: 30, humidity: 82, notes: 'Post-monsoon humid conditions. Light showers in morning but cleared by 9am.' },
        teamPresent: [
          { user: field1._id, role: 'Field Director' },
          { user: admin._id, role: 'Senior Advisor' },
        ],
        depth: { from: 0.0, to: 4.2, layer: 'Dockyard Wall â€“ In Situ', description: 'Structural survey of Harappan dockyard wall system' },
        findings: 'West dockyard wall fully surveyed. Sluice gate mechanism documented. 3D photogrammetric model completed at 0.8mm resolution for ASI digital heritage platform.',
        createdBy: field1._id,
        isPublic: true,
      },

      // AJANTA logs
      {
        site: ajanta._id,
        title: 'Multispectral Imaging Campaign â€” Caves 1 and 17',
        date: new Date('2024-06-05'),
        content: '<p>First multispectral imaging campaign of the Ajanta project. Dr. Rajesh Sharma and Dr. Sunita Deshmukh focused on the south wall of Cave 1 (Mahajanaka Jataka) and the west wall of Cave 17 (Visvantara Jataka) using a DSLR with multispectral filter wheel (UV-fluorescence, VNIR, SWIR).</p><p>The Cave 17 results are extraordinary: a previously unrecognised composition is emerging in the SWIR band on the lower register â€” a partially overpainted scene showing what appears to be a merchant caravan narrative (possibly another Jataka scene), never recorded in the published literature on Cave 17. The Cave 1 painting fragment (AJT-ART-001) shows a detailed underdrawing in red ochre beneath the final black outline â€” providing rare insight into the compositional process of the Ajanta workshop.</p>',
        weather: { condition: 'Hot', temperature: 36, humidity: 40, notes: 'Pre-monsoon heat. Cave interiors significantly cooler (26Â°C). Portable LED flood panels used for even cave illumination during imaging.' },
        teamPresent: [
          { user: admin._id, role: 'Conservation Director' },
          { user: lead2._id, role: 'Imaging Specialist' },
        ],
        depth: { from: 0.0, to: 0.0, layer: 'Surface Documentation (Non-Invasive)', description: 'Cave wall painting multispectral imaging' },
        findings: 'Unknown overpainted scene detected in Cave 17 via SWIR imaging. Cave 1 underdrawing documented for first time. Data sent to IIT Bombay for full analysis.',
        createdBy: admin._id,
        isPublic: true,
      },

      // MEHRGARH logs
      {
        site: mehrgarh._id,
        title: 'Stratigraphic Test Pit MGH-TP1: Early Aceramic Neolithic Horizons',
        date: new Date('2024-02-14'),
        content: '<p>Initiated test pit TP1 (3x3m) at the eastern perimeter of the outpost survey zone. At 1.2m depth, encountered dense organic-rich ashy layers alternating with rammed-earth activity surfaces. Recovered charred emmer wheat (Triticum dicoccum) grains and microlithic blades of banded chert.</p><p>A grinding stone slab with red ochre staining was documented in situ. Soil flotation samples collected for archaeobotanical analysis at BSIP. Clear stratigraphic continuity observed confirming early Neolithic pastoral-farming transitions.</p>',
        depth: { from: 0.8, to: 1.4, layer: 'Layer 3 – Early Aceramic Neolithic', description: 'Ashy midden deposits and domestic hearths' },
        findings: 'Charred emmer wheat grains, chert microliths, grinding slab with ochre residue, bone awls.',
        weather: { condition: 'Sunny', temperature: 24, humidity: 30, notes: 'Clear skies, mild desert wind.' },
        teamPresent: [{ user: lead2._id, role: 'Principal Investigator' }],
        createdBy: lead2._id,
        isPublic: true,
      },
      {
        site: mehrgarh._id,
        title: 'Trench MGH-B2: Terracotta Figurine and Granary Wall Discovery',
        date: new Date('2024-03-02'),
        content: '<p>Excavation of Trench B2 exposed a rectilinear mud-brick compartment wall foundation (30cm width, sun-dried brick 40x20x10cm). Within compartment C-2, an anthropomorphic terracotta female figurine fragment was recovered alongside charred barley seeds.</p><p>The structural layout strongly resembles the multi-roomed storage granaries identified in classic Mehrgarh Period II. High-resolution photogrammetry completed before covering for protective backfill.</p>',
        depth: { from: 1.4, to: 2.1, layer: 'Layer 4 – Mud-brick Architecture Horizon', description: 'Rectilinear compartmental granary structure' },
        findings: 'Terracotta mother-goddess figurine fragment, compartmental granary walls, charred six-row barley.',
        weather: { condition: 'Hot', temperature: 31, humidity: 25, notes: 'Dry afternoon heat.' },
        teamPresent: [{ user: lead2._id, role: 'Principal Investigator' }],
        createdBy: lead2._id,
        isPublic: true,
      },

      // TAXILA logs
      {
        site: taxila._id,
        title: 'Monastic Cell TXL-C4: Gandharan Schist Relief Uncovered',
        date: new Date('2024-03-28'),
        content: '<p>Resumed excavation in the monastic residential quadrangle. Monastic cell C4 revealed intact diaper-masonry stone walls with lime plaster facing. At floor level (0.8m below debris surface), uncovered a fine gray schist relief panel depicting the Great Departure of Prince Siddhartha.</p><p>Traces of original gold leaf gilding remain on the halo and horse harness. A copper coin of Kanishka I was found nearby in the destruction rubble, providing a firm terminus post quem of the 2nd century CE.</p>',
        depth: { from: 0.5, to: 0.9, layer: 'Monastic Cell Occupation Floor', description: 'Diaper masonry room with collapsed ceiling' },
        findings: 'Schist stone relief of the Great Departure, gold leaf traces, copper coin of Kanishka I.',
        weather: { condition: 'Cloudy', temperature: 19, humidity: 55, notes: 'Cool spring morning in foothill valley.' },
        teamPresent: [{ user: admin._id, role: 'Senior Advisor' }],
        createdBy: admin._id,
        isPublic: true,
      },
      {
        site: taxila._id,
        title: 'Stupa Courtyard Prospection: Relic Casket Chamber Assessment',
        date: new Date('2024-04-12'),
        content: '<p>Non-destructive micro-drilling and endoscopic inspection of the south stupa plinth completed. The central relic depository chamber was located at 1.4m depth beneath the umbrella shaft alignment.</p><p>Steatite cylindrical casket and fragmentary Kharosthi inscription on copper sheet recorded. Micro-climate monitoring sensors installed to preserve fragile organic and textile relic wrappings before full conservation lifting.</p>',
        depth: { from: 1.0, to: 1.6, layer: 'Core Stupa Deposit', description: 'Internal relic chamber in limestone bedrock' },
        findings: 'Steatite relic casket, inscribed copper plate in Kharosthi, silk relic wrapping fibers.',
        weather: { condition: 'Sunny', temperature: 23, humidity: 48, notes: 'Optimal visibility.' },
        teamPresent: [{ user: admin._id, role: 'Senior Advisor' }],
        createdBy: admin._id,
        isPublic: true,
      },
    ]);

    console.log(`âœ… Created ${logs.length} field logs.`);

    // â”€â”€ Summary â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    console.log('\nðŸŽ‰ ArchaeoTrack Indian Archaeology Demo Seed Complete!');
    console.log('â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•');
    console.log(`  ðŸ‘¤ Users            : ${usersRaw.length}`);
    console.log(`  ðŸ›ï¸  Excavation Sites : ${sitesRaw.length}`);
    console.log(`  ðŸº Artifacts        : ${artifacts.length}`);
    console.log(`  ðŸ“‹ Field Logs       : ${logs.length}`);
    console.log('â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•');
    console.log('\nðŸ“§ Login Credentials:');
    console.log('  Admin       : admin@archrecords.com  / password123');
    console.log('  Lead Arch   : lead@archrecords.com   / password123');
    console.log('  Field Asst  : field@archrecords.com  / password123');
    console.log('  Researcher  : sunita@archrecords.com / password123');
    console.log('  Viewer      : viewer@archrecords.com / password123');

    await mongoose.connection.close();
    console.log('\nâœ… Database connection closed. Seeding complete!');
    process.exit(0);

  } catch (err) {
    console.error('âŒ Seeding failed:', err.message);
    if (err.errors) {
      Object.keys(err.errors).forEach(key => {
        console.error(`  Field: ${key} â€” ${err.errors[key].message}`);
      });
    }
    await mongoose.connection.close();
    process.exit(1);
  }
};

seedData();
